name: Build and push to Docker Hub as outlandish/wordpress:latest

on:
  push:
    branches: [main]
  schedule:
    - cron: '17 2 * * *'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: "Build and push 'latest' (8.1 / default tag)"
        id: docker_build_latest
        uses: docker/build-push-action@v4
        with:
          push: true
          file: ./php8.1/Dockerfile
          tags: outlandish/wordpress:latest
      -
        name: Build and push php7.4
        id: docker_build_php7_4
        uses: docker/build-push-action@v4
        with:
          push: true
          file: ./php7.4/Dockerfile
          tags: outlandish/wordpress:php7.4
      -
        name: Build and push php8.0
        id: docker_build_php8_0
        uses: docker/build-push-action@v4
        with:
          push: true
          file: ./php8.0/Dockerfile
          tags: outlandish/wordpress:php8.0
      -
        name: Build and push php8.1
        id: docker_build_php8_1
        uses: docker/build-push-action@v4
        with:
          push: true
          file: ./php8.1/Dockerfile
          tags: outlandish/wordpress:php8.1
      -
        name: Build and push php8.2
        id: docker_build_php8_2
        uses: docker/build-push-action@v4
        with:
          push: true
          file: ./php8.2/Dockerfile
          tags: outlandish/wordpress:php8.2
