name: Build and push to Docker Hub as outlandish/wordpress-dev:latest

on:
  push:
    branches: [master]
  schedule:
    - cron: '17 2 * * *'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: "Build and push 'latest' (7.2 / default tag)"
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: outlandish/wordpress:latest
      -
        name: Build and push php7.2
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./php7.2
          tags: outlandish/wordpress:php7.2
      -
        name: Build and push php7.3
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./php7.3
          tags: outlandish/wordpress:php7.3
      -
        name: Build and push php7.4
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./php7.4
          tags: outlandish/wordpress:php7.4
